apiVersion: v1
kind: Service
metadata:
  name: canary-client-service
  namespace: "{{ .Values.tumid }}-devops26"
spec:
  selector:
    app: canary-canteen-client-selector
  ports:
    - port: {{ .Values.canary_client.service.port }}
      targetPort: {{ .Values.canary_client.service.targetPort }}
      protocol: TCP
  type: {{ .Values.canary_client.service.type }}